version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_hetmo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hetmo_app
    ports:
      - "3308:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hetmo_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=hetmo_app
      - JWT_SECRET=hetmo_app_secret_key
    env_file:
      - .env.docker
    restart: unless-stopped
